// <auto-generated />
using System;
using Library_project.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Library_project.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20230415045106_tableCreation")]
    partial class tableCreation
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Library_project.Data.Objects.Location", b =>
                {
                    b.Property<int>("r")
                        .HasColumnType("integer");

                    b.ToTable("Location");
                });

            modelBuilder.Entity("Library_project.Models.audiobook", b =>
                {
                    b.Property<int>("audiobookid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("audiobookid"));

                    b.Property<string>("author")
                        .HasColumnType("text");

                    b.Property<int>("genre")
                        .HasColumnType("integer");

                    b.Property<bool>("is_available")
                        .HasColumnType("boolean");

                    b.Property<TimeOnly>("length")
                        .HasColumnType("time without time zone");

                    b.Property<int>("mediaid")
                        .HasColumnType("integer");

                    b.Property<string>("narrator")
                        .HasColumnType("text");

                    b.Property<string>("title")
                        .HasColumnType("text");

                    b.HasKey("audiobookid");

                    b.HasIndex("mediaid");

                    b.ToTable("audiobook");
                });

            modelBuilder.Entity("Library_project.Models.book", b =>
                {
                    b.Property<int>("bookid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("bookid"));

                    b.Property<string[]>("author")
                        .HasColumnType("text[]");

                    b.Property<int>("copynumber")
                        .HasColumnType("integer");

                    b.Property<int>("genres")
                        .HasColumnType("integer");

                    b.Property<bool>("is_available")
                        .HasColumnType("boolean");

                    b.Property<long>("isbn")
                        .HasColumnType("bigint");

                    b.Property<int>("mediaid")
                        .HasColumnType("integer");

                    b.Property<int>("pagecount")
                        .HasColumnType("integer");

                    b.Property<DateOnly>("publicdate")
                        .HasColumnType("date");

                    b.Property<string>("title")
                        .HasColumnType("text");

                    b.HasKey("bookid");

                    b.HasIndex("mediaid");

                    b.ToTable("books");
                });

            modelBuilder.Entity("Library_project.Models.computer", b =>
                {
                    b.Property<int>("serialnumber")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("serialnumber"));

                    b.Property<bool>("availibility")
                        .HasColumnType("boolean");

                    b.Property<string>("brand")
                        .HasColumnType("text");

                    b.Property<string>("description")
                        .HasColumnType("text");

                    b.Property<int>("mediaid")
                        .HasColumnType("integer");

                    b.HasKey("serialnumber");

                    b.HasIndex("mediaid");

                    b.ToTable("computers");
                });

            modelBuilder.Entity("Library_project.Models.employee", b =>
                {
                    b.Property<int>("employeeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("employeeId"));

                    b.Property<string>("address")
                        .HasColumnType("text");

                    b.Property<DateOnly>("birthday")
                        .HasColumnType("date");

                    b.Property<string>("email")
                        .HasColumnType("text");

                    b.Property<int?>("employee")
                        .HasColumnType("integer");

                    b.Property<string>("first_name")
                        .HasColumnType("text");

                    b.Property<string>("last_name")
                        .HasColumnType("text");

                    b.Property<string>("middle_name")
                        .HasColumnType("text");

                    b.Property<string>("password")
                        .HasColumnType("text");

                    b.Property<string>("phone_number")
                        .HasColumnType("text");

                    b.Property<string>("position")
                        .HasColumnType("text");

                    b.Property<float>("salary")
                        .HasColumnType("real");

                    b.Property<int>("supervisorid")
                        .HasColumnType("integer");

                    b.HasKey("employeeId");

                    b.HasIndex("employee");

                    b.ToTable("employees");
                });

            modelBuilder.Entity("Library_project.Models.historian", b =>
                {
                    b.Property<int>("historian_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("historian_id"));

                    b.Property<DateOnly>("birthday")
                        .HasColumnType("date");

                    b.Property<string>("education")
                        .HasColumnType("text");

                    b.Property<string>("expertise")
                        .HasColumnType("text");

                    b.Property<string>("first_name")
                        .HasColumnType("text");

                    b.Property<string>("last_name")
                        .HasColumnType("text");

                    b.Property<string>("middle_name")
                        .HasColumnType("text");

                    b.HasKey("historian_id");

                    b.ToTable("historians");
                });

            modelBuilder.Entity("Library_project.Models.journal", b =>
                {
                    b.Property<int>("jouranalid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("jouranalid"));

                    b.Property<bool>("availabilty")
                        .HasColumnType("boolean");

                    b.Property<int>("length")
                        .HasColumnType("integer");

                    b.Property<int>("mediaid")
                        .HasColumnType("integer");

                    b.Property<DateOnly>("releasedate")
                        .HasColumnType("date");

                    b.Property<string[]>("researchers")
                        .HasColumnType("text[]");

                    b.Property<string[]>("subject")
                        .HasColumnType("text[]");

                    b.Property<string>("title")
                        .HasColumnType("text");

                    b.HasKey("jouranalid");

                    b.HasIndex("mediaid");

                    b.ToTable("journals");
                });

            modelBuilder.Entity("Library_project.Models.media", b =>
                {
                    b.Property<int>("mediaid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("mediaid"));

                    b.Property<string>("mediaType")
                        .HasColumnType("text");

                    b.HasKey("mediaid");

                    b.ToTable("media");
                });

            modelBuilder.Entity("Library_project.Models.movie", b =>
                {
                    b.Property<int>("movieid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("movieid"));

                    b.Property<bool>("availabilty")
                        .HasColumnType("boolean");

                    b.Property<string>("director")
                        .HasColumnType("text");

                    b.Property<int>("genres")
                        .HasColumnType("integer");

                    b.Property<TimeOnly>("length")
                        .HasColumnType("time without time zone");

                    b.Property<int>("mediaid")
                        .HasColumnType("integer");

                    b.Property<int>("rating")
                        .HasColumnType("integer");

                    b.Property<DateOnly>("releasedate")
                        .HasColumnType("date");

                    b.Property<string>("title")
                        .HasColumnType("text");

                    b.HasKey("movieid");

                    b.HasIndex("mediaid");

                    b.ToTable("movies");
                });

            modelBuilder.Entity("Library_project.Models.projector", b =>
                {
                    b.Property<int>("serialnumber")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("serialnumber"));

                    b.Property<bool>("availability")
                        .HasColumnType("boolean");

                    b.Property<string>("brand")
                        .HasColumnType("text");

                    b.Property<string>("description")
                        .HasColumnType("text");

                    b.Property<int>("lumens")
                        .HasColumnType("integer");

                    b.Property<int>("mediaid")
                        .HasColumnType("integer");

                    b.HasKey("serialnumber");

                    b.HasIndex("mediaid");

                    b.ToTable("projectors");
                });

            modelBuilder.Entity("Library_project.Models.review", b =>
                {
                    b.Property<int>("review_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("review_id"));

                    b.Property<string>("evaluation")
                        .HasColumnType("text");

                    b.Property<int>("library_card_number")
                        .HasColumnType("integer");

                    b.Property<int>("mediaid")
                        .HasColumnType("integer");

                    b.Property<int?>("rating")
                        .HasColumnType("integer");

                    b.HasKey("review_id");

                    b.HasIndex("library_card_number");

                    b.HasIndex("mediaid");

                    b.ToTable("reviews");
                });

            modelBuilder.Entity("Library_project.Models.student", b =>
                {
                    b.Property<int>("library_card_number")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("library_card_number"));

                    b.Property<string>("address")
                        .HasColumnType("text");

                    b.Property<DateOnly>("birthday")
                        .HasColumnType("date");

                    b.Property<string>("email")
                        .HasColumnType("text");

                    b.Property<string>("first_name")
                        .HasColumnType("text");

                    b.Property<int?>("historian_id")
                        .HasColumnType("integer");

                    b.Property<string>("last_name")
                        .HasColumnType("text");

                    b.Property<string>("middle_name")
                        .HasColumnType("text");

                    b.Property<float>("overdue_fees")
                        .HasColumnType("real");

                    b.Property<string>("password")
                        .HasColumnType("text");

                    b.Property<string>("phone_number")
                        .HasColumnType("text");

                    b.HasKey("library_card_number");

                    b.HasIndex("historian_id");

                    b.ToTable("students");
                });

            modelBuilder.Entity("Library_project.Models.audiobook", b =>
                {
                    b.HasOne("Library_project.Models.media", "media")
                        .WithMany()
                        .HasForeignKey("mediaid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("media");
                });

            modelBuilder.Entity("Library_project.Models.book", b =>
                {
                    b.HasOne("Library_project.Models.media", "media")
                        .WithMany()
                        .HasForeignKey("mediaid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("media");
                });

            modelBuilder.Entity("Library_project.Models.computer", b =>
                {
                    b.HasOne("Library_project.Models.media", "media")
                        .WithMany()
                        .HasForeignKey("mediaid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("media");
                });

            modelBuilder.Entity("Library_project.Models.employee", b =>
                {
                    b.HasOne("Library_project.Models.employee", "supervisor")
                        .WithMany()
                        .HasForeignKey("employee");

                    b.Navigation("supervisor");
                });

            modelBuilder.Entity("Library_project.Models.journal", b =>
                {
                    b.HasOne("Library_project.Models.media", "media")
                        .WithMany()
                        .HasForeignKey("mediaid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("media");
                });

            modelBuilder.Entity("Library_project.Models.movie", b =>
                {
                    b.HasOne("Library_project.Models.media", "media")
                        .WithMany()
                        .HasForeignKey("mediaid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("media");
                });

            modelBuilder.Entity("Library_project.Models.projector", b =>
                {
                    b.HasOne("Library_project.Models.media", "media")
                        .WithMany()
                        .HasForeignKey("mediaid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("media");
                });

            modelBuilder.Entity("Library_project.Models.review", b =>
                {
                    b.HasOne("Library_project.Models.student", "student")
                        .WithMany()
                        .HasForeignKey("library_card_number")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Library_project.Models.media", "media")
                        .WithMany()
                        .HasForeignKey("mediaid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("media");

                    b.Navigation("student");
                });

            modelBuilder.Entity("Library_project.Models.student", b =>
                {
                    b.HasOne("Library_project.Models.historian", null)
                        .WithMany("students_to_see")
                        .HasForeignKey("historian_id");
                });

            modelBuilder.Entity("Library_project.Models.historian", b =>
                {
                    b.Navigation("students_to_see");
                });
#pragma warning restore 612, 618
        }
    }
}
